import {
  SENTINEL_COG_PREVIEW_PROVIDER_ID,
  SENTINEL_SEN2SR_PMTILES_PROVIDER_ID
} from "@/lib/imagerySources";
import {
  ERA5_CDS_PROVIDER_ID,
  NASA_POWER_SOLAR_PROVIDER_ID,
  OPEN_METEO_PROVIDER_ID,
  TERRAIN_FLOOD_PROVIDER_ID
} from "@/lib/macroSources";
import { MAPTERHORN_PROVIDER_ID, MAPZEN_PROVIDER_ID } from "@/lib/terrainSources";
import type { MacroLayerDefinition } from "@/lib/layer-catalog/types";

function layer(definition: MacroLayerDefinition): MacroLayerDefinition {
  return definition;
}

export const macroLayerCatalog: MacroLayerDefinition[] = [
  layer({
    id: "terrain-elevation",
    label: "Elevation",
    category: "terrain",
    description: "Open DEM/DTM-aware elevation surface from Mapterhorn or fallback terrain.",
    providerIds: [MAPTERHORN_PROVIDER_ID, MAPZEN_PROVIDER_ID],
    readiness: "active-runtime",
    status: "active",
    sourceType: "static",
    visualizationType: "raster",
    defaultOpacity: 0.82,
    attribution: "Mapterhorn, Mapzen/Joerd, and upstream terrain contributors",
    license: "Open terrain attributions required; source-specific notices preserved",
    freshness: "provider archive",
    confidence: 68,
    limitations: "Generic DEM by default unless a regional source proves bare-earth DTM semantics.",
    mapReady: true,
    preprocessingRequired: false,
    publicDemoSafe: true
  }),
  layer({
    id: "terrain-hillshade",
    label: "Hillshade",
    category: "terrain",
    description: "Relief shading derived from the active raster-dem provider.",
    providerIds: [MAPTERHORN_PROVIDER_ID, MAPZEN_PROVIDER_ID],
    readiness: "active-runtime",
    status: "active",
    sourceType: "derived",
    visualizationType: "hillshade",
    defaultOpacity: 0.5,
    attribution: "Derived from active DEM provider",
    license: "Derived output inherits active terrain attribution and license notes",
    freshness: "runtime derived",
    confidence: 62,
    limitations: "Hillshade communicates shape; it is not a terrain-truth upgrade.",
    mapReady: true,
    preprocessingRequired: false,
    publicDemoSafe: true
  }),
  layer({
    id: "terrain-contours",
    label: "Contours",
    category: "terrain",
    description: "Contour provider contract for future precomputed vector contour PMTiles.",
    providerIds: ["precomputed-contours-pmtiles"],
    readiness: "broker-planned",
    status: "fallback",
    sourceType: "future-provider",
    visualizationType: "contour",
    defaultOpacity: 0.36,
    attribution: "Future derived contour tiles",
    license: "Input DEM/DTM license applies",
    freshness: "pending preprocessing",
    confidence: 35,
    limitations:
      "Contours are not extracted live in the browser; production needs precomputed vector tiles.",
    mapReady: false,
    preprocessingRequired: true,
    publicDemoSafe: true
  }),
  layer({
    id: "terrain-slope",
    label: "Slope",
    category: "terrain",
    description: "Slope-ready terrain product boundary for future package workers.",
    providerIds: [TERRAIN_FLOOD_PROVIDER_ID],
    readiness: "broker-planned",
    status: "unavailable",
    sourceType: "future-provider",
    visualizationType: "raster",
    defaultOpacity: 0.48,
    attribution: "Future DEM/DTM preprocessing",
    license: "Input terrain license applies",
    freshness: "pending preprocessing",
    confidence: 32,
    limitations: "Requires DEM/DTM preprocessing outside the browser before display.",
    mapReady: false,
    preprocessingRequired: true,
    publicDemoSafe: true
  }),
  layer({
    id: "terrain-aspect",
    label: "Aspect",
    category: "terrain",
    description: "Aspect-ready terrain product boundary for solar and land-context layers.",
    providerIds: [TERRAIN_FLOOD_PROVIDER_ID],
    readiness: "broker-planned",
    status: "unavailable",
    sourceType: "future-provider",
    visualizationType: "raster",
    defaultOpacity: 0.44,
    attribution: "Future DEM/DTM preprocessing",
    license: "Input terrain license applies",
    freshness: "pending preprocessing",
    confidence: 32,
    limitations: "Requires preprocessing into a tile or H3 summary product.",
    mapReady: false,
    preprocessingRequired: true,
    publicDemoSafe: true
  }),
  layer({
    id: "climate-weather",
    label: "Weather",
    category: "climate",
    description: "Selected-cell weather context from Open-Meteo with deterministic fallback.",
    providerIds: [OPEN_METEO_PROVIDER_ID],
    readiness: "active-runtime",
    status: "fallback",
    sourceType: "live",
    visualizationType: "h3",
    defaultOpacity: 0.54,
    attribution: "Open-Meteo",
    license: "No-key prototype use; verify terms before production",
    freshness: "selected cell live/cache/mock",
    confidence: 70,
    limitations: "Point forecast context only, not an official warning feed.",
    mapReady: true,
    preprocessingRequired: false,
    publicDemoSafe: true
  }),
  layer({
    id: "climate-heat",
    label: "Heat",
    category: "climate",
    description: "Heat stress context from weather and future climate-normal summaries.",
    providerIds: [OPEN_METEO_PROVIDER_ID, ERA5_CDS_PROVIDER_ID],
    readiness: "broker-planned",
    status: "fallback",
    sourceType: "derived",
    visualizationType: "h3",
    defaultOpacity: 0.5,
    attribution: "Open-Meteo / future ERA5-derived summaries",
    license: "Provider-specific",
    freshness: "mock/derived",
    confidence: 52,
    limitations: "Heat context needs local calibration before it can drive decisions.",
    mapReady: true,
    preprocessingRequired: true,
    publicDemoSafe: true
  }),
  layer({
    id: "climate-rainfall",
    label: "Rainfall",
    category: "climate",
    description: "Rainfall and precipitation context from forecast or preprocessed grids.",
    providerIds: [OPEN_METEO_PROVIDER_ID],
    readiness: "broker-planned",
    status: "fallback",
    sourceType: "derived",
    visualizationType: "h3",
    defaultOpacity: 0.5,
    attribution: "Open-Meteo / future gridded forecast sources",
    license: "Provider-specific",
    freshness: "mock/selected-cell",
    confidence: 54,
    limitations: "Selected-cell forecast context only until gridded H3 summaries exist.",
    mapReady: true,
    preprocessingRequired: false,
    publicDemoSafe: true
  }),
  layer({
    id: "hazard-fire-weather",
    label: "Fire weather",
    category: "hazard",
    description: "Fire-weather context from weather, vegetation, wind, and future FIRMS inputs.",
    providerIds: [OPEN_METEO_PROVIDER_ID, "nasa-firms-active-fire"],
    readiness: "broker-planned",
    status: "fallback",
    sourceType: "derived",
    visualizationType: "h3",
    defaultOpacity: 0.52,
    attribution: "Open-Meteo / future NASA FIRMS",
    license: "Provider-specific; FIRMS access review required",
    freshness: "mock/derived",
    confidence: 48,
    limitations: "Decision-support context only, not an official fire warning or risk map.",
    mapReady: true,
    preprocessingRequired: true,
    publicDemoSafe: true
  }),
  layer({
    id: "hazard-flood-lowland",
    label: "Flood / lowland",
    category: "hazard",
    description: "Flood/lowland context scaffold from terrain, water proximity, and rainfall.",
    providerIds: [TERRAIN_FLOOD_PROVIDER_ID],
    readiness: "broker-planned",
    status: "fallback",
    sourceType: "derived",
    visualizationType: "h3",
    defaultOpacity: 0.5,
    attribution: "Derived from future DEM/HAND/water/rainfall inputs",
    license: "Input-provider terms apply",
    freshness: "mock/derived",
    confidence: 42,
    limitations:
      "Not an authoritative flood map; requires HAND/hydro preprocessing and validation.",
    mapReady: true,
    preprocessingRequired: true,
    publicDemoSafe: true
  }),
  layer({
    id: "hazard-drought",
    label: "Drought",
    category: "hazard",
    description: "Drought context boundary from weather, soil moisture, and climate datasets.",
    providerIds: [ERA5_CDS_PROVIDER_ID],
    readiness: "broker-planned",
    status: "unavailable",
    sourceType: "future-provider",
    visualizationType: "h3",
    defaultOpacity: 0.46,
    attribution: "Future ERA5/NASA/soil-moisture-derived summaries",
    license: "Provider-specific",
    freshness: "pending preprocessing",
    confidence: 34,
    limitations: "No live drought data in this phase.",
    mapReady: false,
    preprocessingRequired: true,
    publicDemoSafe: true
  }),
  layer({
    id: "solar-potential",
    label: "Solar potential",
    category: "solar",
    description: "Solar practicality context from NASA POWER and terrain products.",
    providerIds: [NASA_POWER_SOLAR_PROVIDER_ID],
    readiness: "broker-planned",
    status: "fallback",
    sourceType: "future-provider",
    visualizationType: "h3",
    defaultOpacity: 0.5,
    attribution: "NASA POWER / future terrain-derived slope/aspect",
    license: "NASA POWER citation and provider terms required",
    freshness: "mock/provider-boundary",
    confidence: 48,
    limitations: "Planning context only, not a bankable solar engineering estimate.",
    mapReady: true,
    preprocessingRequired: true,
    publicDemoSafe: true
  }),
  layer({
    id: "vegetation-ndvi",
    label: "NDVI",
    category: "vegetation",
    description: "Vegetation greenness summary from Sentinel/landcover imagery manifests.",
    providerIds: [SENTINEL_COG_PREVIEW_PROVIDER_ID, SENTINEL_SEN2SR_PMTILES_PROVIDER_ID],
    readiness: "payload-ready",
    status: "fallback",
    sourceType: "derived",
    visualizationType: "h3",
    defaultOpacity: 0.48,
    attribution: "Copernicus Sentinel-2 and derived indexes",
    license: "Sentinel attribution and derived-output provenance required",
    freshness: "mock manifest",
    confidence: 58,
    limitations: "Broad vegetation context only; not individual-tree or parcel-scale truth.",
    mapReady: true,
    preprocessingRequired: true,
    publicDemoSafe: true
  }),
  layer({
    id: "vegetation-ndwi",
    label: "NDWI",
    category: "vegetation",
    description: "Water/vegetation index summary from Sentinel imagery manifests.",
    providerIds: [SENTINEL_COG_PREVIEW_PROVIDER_ID, SENTINEL_SEN2SR_PMTILES_PROVIDER_ID],
    readiness: "payload-ready",
    status: "fallback",
    sourceType: "derived",
    visualizationType: "h3",
    defaultOpacity: 0.48,
    attribution: "Copernicus Sentinel-2 and derived indexes",
    license: "Sentinel attribution and derived-output provenance required",
    freshness: "mock manifest",
    confidence: 56,
    limitations: "Water proxy context only; verify with source-backed hydrography.",
    mapReady: true,
    preprocessingRequired: true,
    publicDemoSafe: true
  }),
  layer({
    id: "vegetation-landcover",
    label: "Land cover",
    category: "vegetation",
    description: "Land-cover context from ESA WorldCover, Dynamic World, or national layers.",
    providerIds: ["esa-worldcover", "dynamic-world"],
    readiness: "broker-planned",
    status: "unavailable",
    sourceType: "future-provider",
    visualizationType: "h3",
    defaultOpacity: 0.44,
    attribution: "Future open land-cover providers",
    license: "Provider-specific",
    freshness: "pending preprocessing",
    confidence: 40,
    limitations: "No live landcover package is active yet.",
    mapReady: false,
    preprocessingRequired: true,
    publicDemoSafe: true
  }),
  layer({
    id: "vegetation-crop-condition",
    label: "Crop condition",
    category: "vegetation",
    description: "Crop/land condition research boundary inspired by Crop Monitor/GEOGLAM.",
    providerIds: ["crop-monitor-geoglam"],
    readiness: "research",
    status: "unavailable",
    sourceType: "future-provider",
    visualizationType: "h3",
    defaultOpacity: 0.44,
    attribution: "Future crop-monitor-style sources",
    license: "Provider-specific; review before use",
    freshness: "research",
    confidence: 30,
    limitations: "Research/provider boundary only; no crop-condition claims in this phase.",
    mapReady: false,
    preprocessingRequired: true,
    publicDemoSafe: true
  }),
  layer({
    id: "imagery-sentinel2",
    label: "Sentinel-2",
    category: "imagery",
    description: "Optional recent clear-scene Sentinel preview layer.",
    providerIds: [SENTINEL_COG_PREVIEW_PROVIDER_ID],
    readiness: "active-runtime",
    status: "fallback",
    sourceType: "static",
    visualizationType: "raster",
    defaultOpacity: 0.58,
    attribution: "Copernicus Sentinel-2 preview providers",
    license: "Preview/service terms require review before production use",
    freshness: "mock preview manifest",
    confidence: 56,
    limitations: "Preview imagery is visual context and not a legal/survey/emergency source.",
    mapReady: true,
    preprocessingRequired: false,
    publicDemoSafe: true
  }),
  layer({
    id: "imagery-sen2sr",
    label: "SEN2SR enhanced",
    category: "imagery",
    description: "Offline/server-generated Sentinel-2 SEN2SR raster product boundary.",
    providerIds: [SENTINEL_SEN2SR_PMTILES_PROVIDER_ID],
    readiness: "payload-ready",
    status: "unavailable",
    sourceType: "future-provider",
    visualizationType: "raster",
    defaultOpacity: 0.58,
    attribution: "Copernicus Sentinel-2 / ESAOpenSR SEN2SR",
    license: "Sentinel and SEN2SR citation/terms required",
    freshness: "pending sidecar output",
    confidence: 44,
    limitations:
      "AI-assisted super-resolution can introduce artifacts and is never measured 2.5 m truth.",
    mapReady: false,
    preprocessingRequired: true,
    publicDemoSafe: true
  })
];
